cpx.sh code refactor
lorypelli/rice pull request #1
Opened 2023-09-28 02:45 UTC by ashrude

I noticed that `cpx.sh` had some opportunity for optimization, so I took it upon myself to refactor it for you.

The new tool is 198.916666667 times faster than previously using a 1gb file, and even more so with larger files. As seen here:

![Screenshot from 2023-09-27 19-27-55](https://github.com/lorypelli/rice/assets/49853479/ecc15f97-7b13-48c9-b698-b5d15fc4079f)

As an added benefit, the updated tool is 38% smaller.

2023-09-28 04:03 UTC, hellidox commented
LGTM

2023-09-28 05:29 UTC, vclemenzi commented
Isn't better creating an alias for the command mv?

The string for `.bashrc` and `.zshrc` is that:
```bash
alias cpx="mv"
```

2023-09-28 13:03 UTC, hellidox requested changes
I think `mv $@` would be better

2023-11-07 20:15 UTC, blyxyas requested changes
@hellidox that's not a good idea. The best thing to do here is automatically install Rust and write

2023-11-07 20:15 UTC, blyxyas commented on utils/cpx.sh
> +mv $1 $2
@hellidox that's not a good idea. The best thing to do here is automatically install Rust and do some code generation, like the pros do.

```suggestion
#!/bin/bash
# Check if Rust is installed, if not, install it
if [ ! command -v rustc ]; then
  # Install Rust
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | 
sh
fi
  touch move.rs
  echo "fn main() { let _ = std::fs::rename($1, $2); }" > move.rs
  rustc move.rs
  
  # Now, let's move the installed binary to /usr/bin
  sudo mv ./move /usr/bin

# Now, we can just use our newly compiled `move` command
move $1 $2

```

2023-11-08 19:33 UTC, hellidox commented on utils/cpx.sh
> +mv $1 $2
Ah, but what if the source and destination are cross-device?

2024-01-31 22:06 UTC, closed without merging